package defaultPackage;

import java.awt.Canvas;

public class Game extends Canvas implements Runnable {
	
	private static final long serialVersionUID = -7812814071227895042L; //auto generated by eclipse, required for java programs

	
	
	
	public void run() {
		
	}

	public static void main(String[] args) {
		
		
	}
}
